[".local/share/zsh/plugins/fast-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/z-shell/F-Sy-H/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/share/zsh/plugins/zsh-completions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/share/zsh/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/share/zsh/plugins/oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/share/asdf"]
    type = "archive"
    url = "https://github.com/asdf-vm/asdf/archive/v0.10.1.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/share/zsh/plugins/fzf"]
    type = "archive"
    url = "https://github.com/junegunn/fzf/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/shell/**"]
